package model;
// Generated Mar 24, 2024, 12:07:53 AM by Hibernate Tools 5.4.33.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ClassTable generated by hbm2java
 */
public class ClassTable implements java.io.Serializable {

	private Integer idClasstable;
	@JsonIgnore
	private ClassExercise classExercise;
	private Date date;
	private Date timeStart;
	private Date timeEnd;
	@JsonIgnore
	private Set reserves = new HashSet(0);

	public ClassTable() {
	}

	public ClassTable(ClassExercise classExercise, Date date, Date timeStart, Date timeEnd) {
		this.classExercise = classExercise;
		this.date = date;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
	}

	public ClassTable(ClassExercise classExercise, Date date, Date timeStart, Date timeEnd, Set reserves) {
		this.classExercise = classExercise;
		this.date = date;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
		this.reserves = reserves;
	}

	public Integer getIdClasstable() {
		return this.idClasstable;
	}

	public void setIdClasstable(Integer idClasstable) {
		this.idClasstable = idClasstable;
	}

	public ClassExercise getClassExercise() {
		return this.classExercise;
	}

	public void setClassExercise(ClassExercise classExercise) {
		this.classExercise = classExercise;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Date getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(Date timeStart) {
		this.timeStart = timeStart;
	}

	public Date getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(Date timeEnd) {
		this.timeEnd = timeEnd;
	}

	public Set getReserves() {
		return this.reserves;
	}

	public void setReserves(Set reserves) {
		this.reserves = reserves;
	}

}
