package model;
// Generated Mar 24, 2024, 12:07:53 AM by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * MemberLevel generated by hbm2java
 */
public class MemberLevel implements java.io.Serializable {

	private Integer idMemberLevel;
	private String leveltype;
	private double price;
	private int numUse;
	private String detail;
	@JsonIgnore
	private Set orderLevels = new HashSet(0);

	public MemberLevel() {
	}

	public MemberLevel(String leveltype, double price, int numUse, String detail) {
		this.leveltype = leveltype;
		this.price = price;
		this.numUse = numUse;
		this.detail = detail;
	}

	public MemberLevel(String leveltype, double price, int numUse, String detail, Set orderLevels) {
		this.leveltype = leveltype;
		this.price = price;
		this.numUse = numUse;
		this.detail = detail;
		this.orderLevels = orderLevels;
	}

	public Integer getIdMemberLevel() {
		return this.idMemberLevel;
	}

	public void setIdMemberLevel(Integer idMemberLevel) {
		this.idMemberLevel = idMemberLevel;
	}

	public String getLeveltype() {
		return this.leveltype;
	}

	public void setLeveltype(String leveltype) {
		this.leveltype = leveltype;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public int getNumUse() {
		return this.numUse;
	}

	public void setNumUse(int numUse) {
		this.numUse = numUse;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public Set getOrderLevels() {
		return this.orderLevels;
	}

	public void setOrderLevels(Set orderLevels) {
		this.orderLevels = orderLevels;
	}

}
