package model;
// Generated Mar 24, 2024, 12:07:53 AM by Hibernate Tools 5.4.33.Final

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Reserve generated by hbm2java
 */
public class Reserve implements java.io.Serializable {

	private Integer idReserve;
	@JsonIgnore
	private ClassTable classTable;
	@JsonIgnore
	private User user;
	private Date date;
	private Date time;
	private String status;

	public Reserve() {
	}

	public Reserve(ClassTable classTable, User user, Date date, Date time, String status) {
		this.classTable = classTable;
		this.user = user;
		this.date = date;
		this.time = time;
		this.status = status;
	}

	public Integer getIdReserve() {
		return this.idReserve;
	}

	public void setIdReserve(Integer idReserve) {
		this.idReserve = idReserve;
	}

	public ClassTable getClassTable() {
		return this.classTable;
	}

	public void setClassTable(ClassTable classTable) {
		this.classTable = classTable;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
