package model;
// Generated Mar 24, 2024, 12:07:53 AM by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ClassExercise generated by hbm2java
 */
public class ClassExercise implements java.io.Serializable {

	private Integer idClass;
	private String name;
	private String detailClass;
	private String trainer;
	private int count;
	@JsonIgnore
	private Set classTables = new HashSet(0);

	public ClassExercise() {
	}

	public ClassExercise(String name, String detailClass, String trainer, int count) {
		this.name = name;
		this.detailClass = detailClass;
		this.trainer = trainer;
		this.count = count;
	}

	public ClassExercise(String name, String detailClass, String trainer, int count, Set classTables) {
		this.name = name;
		this.detailClass = detailClass;
		this.trainer = trainer;
		this.count = count;
		this.classTables = classTables;
	}

	public Integer getIdClass() {
		return this.idClass;
	}

	public void setIdClass(Integer idClass) {
		this.idClass = idClass;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDetailClass() {
		return this.detailClass;
	}

	public void setDetailClass(String detailClass) {
		this.detailClass = detailClass;
	}

	public String getTrainer() {
		return this.trainer;
	}

	public void setTrainer(String trainer) {
		this.trainer = trainer;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public Set getClassTables() {
		return this.classTables;
	}

	public void setClassTables(Set classTables) {
		this.classTables = classTables;
	}

}
